# Generated by Django 4.2.27 on 2026-01-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_comment_postlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.city'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
