# Generated by Django 4.2.27 on 2026-01-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_bio_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.TextField(blank=True, default='en', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
