# Generated by Django 4.2.27 on 2026-01-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_comment_postlike_and_more'),
        ('core', '0005_alter_user_created_at_alter_user_language_preference_and_more'),
    ]

    operations = [
    ]
