# Generated by Django 4.2.27 on 2026-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260103_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attractions_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
